### ISSUE TITLE
get the table name 

### ISSUE THREAD

**Issue by gmluckly** [rusuly/mysql_cdc#2]
Is there a good way to filter table names? such as the canal do.

**Comment by rusuly** [comment]
Hi, sorry for late response.

There is no feature to filter tables in the library, but you can manually filter rows based on what table the row belongs to, see [the C# issue](https://github.com/rusuly/MySqlCdc/issues/19)

Unfortunately, right now the repository is not maintained because of russian invasion of Ukraine.
